title: Heat Stress and Adverse Obstetric Outcomes
subtitle: Exploring Associations Between Extreme Heat and Adverse Obstetrict Outcomes in India
description: A responsive site template designed by HTML5 Up and released under the Creative Commons.
remote_theme: pages-themes/cayman@v0.2.0
