title: Heat Stress and Adverse Obstetric Outcomes in India
description: Exploring Associations Between Extreme Heat and Adverse Obstetric Outcomes in India
remote_theme: pages-themes/minimal@v0.2.0
github:
  is_project_page: false
